apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM= # "postgres" được mã hóa Base64
  POSTGRES_PASSWORD: cG9zdGdyZXM= # "postgres" được mã hóa Base64
  PGPASSWORD: dmlldHR1 # "viettu" được mã hóa Base64
